language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run build

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
